name: beauty_camera_plugin_example
description: "Demonstrates how to use the beauty_camera_plugin plugin."

publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  beauty_camera_plugin:
    path: ../

  cupertino_icons: ^1.0.8
  video_player: ^2.9.5
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
