name: beauty_camera_plugin
description: "A Flutter plugin for implementing beauty camera functionality with filters and effects"
version: 0.0.1
homepage: https://github.com/tuanvm98/beauty_camera_plugin

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pigeon: ^25.3.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.beauty.camera_plugin
        pluginClass: BeautyCameraPlugin
      ios:
        package: com.beauty.camera_plugin
        pluginClass: BeautyCameraPlugin
